version: "3.9"

services:
  app:
    build: .
    container_name: express_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB=${DB}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
